services:
  postgres:
    image: postgres:15
    container_name: fiapcloudgames-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiapcloudgames
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./src/FiapCloudGames.Promocoes.API/Dockerfile
    image: fcg-app
    container_name: fiapcloudgames-api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=fiapcloudgames;Username=admin;Password=admin123
      - ASPNETCORE_URLS=http://+:5000

volumes:
  postgres_data:
