services:
  api:
    build:
      context: .
      dockerfile: ./src/FiapCloudGames.Promocoes.API/Dockerfile
    image: fcg-app
    container_name: fiapcloudgames-api
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=fiapcloudgames;Username=admin;Password=admin123
      - ASPNETCORE_URLS=http://+:5002

volumes:
  postgres_data:
